/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class git_wpy_format_vector_OffHeapUtils */

#ifndef _Included_git_wpy_format_vector_OffHeapUtils
#define _Included_git_wpy_format_vector_OffHeapUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    allocateColumn
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_git_wpy_format_vector_OffHeapUtils_allocateColumn
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setNullAt
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setNullAt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setByte
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setByte
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setShort
 * Signature: (JJS)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setShort
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setInt
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setInt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setLong
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setFloat
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setByteArray
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setByteArray__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    setByteArray
 * Signature: (JJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_setByteArray__JJLjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[BI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3BI
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[ZI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3ZI
  (JNIEnv *, jclass, jlong, jlong, jbooleanArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[SI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3SI
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[CI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3CI
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[II)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3II
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[JI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3JI
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[FI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3FI
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    bulkPut
 * Signature: (JJ[DI)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_bulkPut__JJ_3DI
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint);

/*
 * Class:     git_wpy_format_vector_OffHeapUtils
 * Method:    freeColumn
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_git_wpy_format_vector_OffHeapUtils_freeColumn
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
